
/*
 * Main.eq
 * Generated by Eqela Studio 2.0b7.4
 */

public class Main : SEScene
{
	SESprite image1;
	SESprite image2;
	SESprite image3;
	SESprite image4;
	SESprite text;
	double opacity;
	public void initialize(SEResourceCache rsc) {
		base.initialize(rsc);
		add_sprite_for_color(Color.instance("blue"),get_scene_width(),get_scene_height());
		
		rsc.prepare_image("mycloud","cloud",0.5*get_scene_width(), 0.5*get_scene_height());
		image1 = add_sprite_for_image(SEImage.for_resource("mycloud"));
		image1.move(0,0);
		
		rsc.prepare_image("myhawk","hawk",get_scene_width()*0.5, get_scene_height()*0.5);
		image2 = add_sprite_for_image(SEImage.for_resource("myhawk"));
		image2.move(get_scene_width()*0.5,0);
		
		rsc.prepare_image("mypillow","yuno",get_scene_width()*0.5, get_scene_height()*0.5);
		image3 = add_sprite_for_image(SEImage.for_resource("mypillow"));
		image3.move(0, get_scene_height()*0.5);
		
		rsc.prepare_image("mytroll","Trollface",get_scene_width()*0.5, get_scene_height()*0.5);
		image4 = add_sprite_for_image(SEImage.for_resource("mytroll"));
		image4.move(get_scene_width()*0.5, get_scene_height()*0.5);

		rsc.prepare_font("myfont","arial bold color=#000043", 40);
		text = add_sprite_for_text(" ","myfont");
	}

	
	public void on_key_press(String name, String str) {
        base.on_key_press(name, str);
		text.set_text("Cloud");
		text.move(get_scene_width()*0.25,get_scene_height()*0.25);
    }

    public void on_pointer_press(SEPointerInfo pi) {
	   base.on_pointer_press(pi);
		if(pi.is_inside(0,0,0.5*get_scene_width(), 0.5*get_scene_height()))
		{
			text.set_text("Cloud");
			text.move(0.25*get_scene_width()-text.get_width()*0.5, 0.25*get_scene_height());
			image1.set_alpha(0.5);
			image2.set_alpha(1);
			image3.set_alpha(1);
			image4.set_alpha(1);		
		}
		else if(pi.is_inside(get_scene_width()*0.5,0,0.5*get_scene_width(), 0.5*get_scene_height()))
		{
			
			text.set_text("Hawk");
			text.move(0.75*get_scene_width()-text.get_width()*0.5, 0.25*get_scene_height());
			image2.set_alpha(0.5);
			image1.set_alpha(1);
			image3.set_alpha(1);
			image4.set_alpha(1);
		}

		else if(pi.is_inside(0,0.5*get_scene_height(),0.5*get_scene_width(), 0.5*get_scene_height()))
		{
		
			text.set_text("Textback");
			text.move(0.25*get_scene_width()-text.get_width()*0.5, 0.75*get_scene_height());
			image3.set_alpha(0.5);
			image1.set_alpha(1);
			image2.set_alpha(1);
			image4.set_alpha(1);
		}

		else if(pi.is_inside(get_scene_width()*0.5,get_scene_height()*0.5,0.5*get_scene_width(), 0.5*get_scene_height()))
		{
		
			text.set_text("Troll");
			text.move(0.75*get_scene_width()-text.get_width()*0.5, 0.75*get_scene_height());
			image4.set_alpha(0.5);
			image2.set_alpha(1);
			image3.set_alpha(1);
			image1.set_alpha(1);	
		}
    }
	public void set_alpha(double alpha)
	{
		opacity = alpha;
	}
}